version: '3.1'
services:
  
  postgres:
    container_name: postgres
    image: postgres:12.1
    env_file: 
      - .env
    volumes:
      - ./.postgresdb/:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: on-failure

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.16
    env_file: 
      - .env
    ports:
      - 5050:80
    restart: on-failure